import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default : "NextJS crash course",
    template : "%s | Template title",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="h-10 w-full bg-pink-800 px-2 py-10">Header</header>
        {children}
        <footer className="h-10 w-full bg-pink-900 px-2 py-10">Footer</footer>
        </body>
    </html>
  );
}
